Toolkit readme update
KennaSecurity/toolkit pull request #489
Opened 2023-06-30 22:14 UTC by slubeckatkenna

README update with usage note regarding new(ish) base64 API keys that contain "$" characters will require escaping when called via shell

2023-07-03 06:42 UTC, rick-kenna requested changes
Agreed, but this also works: `export='123456ABCDEF$'`.  I think this is simplier and should be used instead or at least both should be mentioned.  You can also point to the [API Authentication](https://apidocs.kennasecurity.com/reference/api-authentication) section.

2023-07-03 15:52 UTC, jgarber-cisco submitted a review, later dismissed
I agree with @rick-kenna that it's preferable to encourage customers to single-quote their API keys in a shell rather than escaping them. It's much more fool-proof!

2023-07-03 16:38 UTC, rick-kenna approved these changes

2023-07-03 17:05 UTC, rick-kenna commented
@jgarber-cisco How is it cryptic?  It is a reference.  And the API documentation discusses the exact point with an example for Linux and Windows.

2023-07-03 17:07 UTC, jgarber-cisco commented
Ok, sorry to be over the top!
________________________________
From: Rick Ehrhart ***@***.***>
Sent: Monday, July 3, 2023 1:05:49 PM
To: KennaSecurity/toolkit ***@***.***>
Cc: Jason Garber (jagarber) ***@***.***>; Mention ***@***.***>
Subject: Re: [KennaSecurity/toolkit] Toolkit readme update (PR #489)


@jgarber-cisco<https://github.com/jgarber-cisco> How is it cryptic? It is a reference. And the API documentation discusses the exact point with an example for Linux and Windows.

—
Reply to this email directly, view it on GitHub<https://github.com/KennaSecurity/toolkit/pull/489#issuecomment-1618896626>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5GQU4KVG6IPTMXUHE2OZYDXOL3W3ANCNFSM6AAAAAAZ2LNEQA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-05 21:39 UTC, slubeckatkenna commented
Ideally we should probably point to Rick's https://github.com/rick-kenna/API_keys_safe_store over storing/exporting plaintext keys but linking out to apidocs should suffice for now. @jgarber-cisco  May I dismiss your changes review in order to merge?

2023-07-05 23:13 UTC, jgarber-cisco approved these changes

2023-07-06 18:49 UTC, merged