Update README.md
KennaSecurity/toolkit pull request #491
Opened 2023-07-13 17:45 UTC by FPolillo

Zeh, I have edited this page to make it more user friendly. Kindly approve it, and then I will just point users to this page from the help.

2023-07-13 20:34 UTC, FPolillo reviewed
I have updated the article to make it more user friendly.

2023-07-13 20:50 UTC, jgarber-cisco requested changes

2023-07-13 20:50 UTC, jgarber-cisco commented on tasks/connectors/edgescan/README.md
> +Fo more detailed inforamtion about running the task, see [here](https://github.com/KennaSecurity/toolkit/blob/master/README.md).
Two typos

2023-07-13 20:50 UTC, jgarber-cisco commented on tasks/connectors/edgescan/README.md
> +To create the correct corresponding Kenna assets, the connector makes use of the data from all theree of the following sources:
Typo

2023-07-13 20:50 UTC, jgarber-cisco commented on tasks/connectors/edgescan/README.md
> +Use this pass env variable to make the task comminicate with `localhost:3000` instead of `live.edgescan.com`:
"Use this environment variable..."

2023-07-14 07:22 UTC, jgarber-cisco approved these changes

2023-07-14 07:27 UTC, merged