CON-3859/update whitehat endpoints
KennaSecurity/toolkit pull request #508
Opened 2023-09-25 22:21 UTC by DegzKS

Use version 2 for getting assets

2023-09-26 14:53 UTC, DegzKS commented on .ruby-version
> +3.2.1
This change was made because the Gemfile and the .ruby-version miss matched

2023-09-26 15:26 UTC, nhenry012 requested changes

2023-09-26 15:26 UTC, nhenry012 commented on tasks/connectors/ntt_sentinel_dynamic/lib/api_client.rb
> +        V1_ASSETS_ENDPOINT = "/asset" # NOTE: deprecation occurs Nov 6th 2023
Is this still needed? Can we remove it?

2023-09-26 15:26 UTC, nhenry012 commented on tasks/connectors/ntt_sentinel_dynamic/lib/mapper.rb
> +          # TODO: investigate why we use the site id (subID)
Lets leave out this TODO.

2023-09-26 15:29 UTC, DegzKS commented on tasks/connectors/ntt_sentinel_dynamic/lib/api_client.rb
> +        V1_ASSETS_ENDPOINT = "/asset" # NOTE: deprecation occurs Nov 6th 2023
No, need it. I will remove it

2023-09-26 15:29 UTC, DegzKS commented on tasks/connectors/ntt_sentinel_dynamic/lib/mapper.rb
> +          # TODO: investigate why we use the site id (subID)
OK

2023-09-26 15:32 UTC, nhenry012 submitted a review, later dismissed

2023-09-28 19:49 UTC, nhenry012 approved these changes

2023-09-29 17:40 UTC, nhenry012 approved these changes

2023-10-02 14:20 UTC, merged

2023-10-02 18:19 UTC, mtmcfarl commented
Unless the creds have already been rotated, this PR exposed the sentinel api key along with the kenna api key in the screenshot.

2023-10-02 18:29 UTC, DegzKS commented
> Unless the creds have already been rotated, this PR exposed the sentinel api key along with the kenna api key in the screenshot.

They have not being rotated yet! I will remove the screenshot and then rotate the Kenna API that I used on STG. 
good catch!